# generated by datamodel-codegen:
#   filename:  user_policy.json
#   timestamp: 2025-12-04T06:31:02+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Op(Enum):
    field__ = "=="
    field___1 = "!="
    field_ = ">"
    field___2 = ">="
    field__1 = "<"
    field___3 = "<="
    field___4 = "<>"
    in_ = "in"
    not_in = "not in"
    has = "has"
    has_not = "has not"


class Filter(BaseModel):
    prop: str | None = None
    op: Op | None = None
    value: str | None = None


class Permission(Enum):
    can_view = "can_view"
    can_edit = "can_edit"
    can_delete = "can_delete"
    can_share = "can_share"


class Effect(Enum):
    allow = "allow"
    deny = "deny"


class UserPolicy(BaseModel):
    filters: list[Filter] | None = None
    description: str | None = None
    permissions: list[Permission]
    effect: Effect


class UserPolicyModel(BaseModel):
    policies: list[UserPolicy]
